### ISSUE TITLE
Wrong links on https://should-i-use-react-or-angular.now.sh/done

### ISSUE THREAD

**Issue by LukyVj** [SaraVieira/should-i-use-react-or-vue#11]
When shared using the twitter button, the link is: "Should I use react or vue" :)

**Comment by SaraVieira** [comment]
Hey!

I didn't make that version :/

**Comment by LukyVj** [comment]
Hey, yeah 😂 My bad, I found out after I mentioned you in a tweet! 

Fun project tho!

**Comment by SaraVieira** [comment]
I don't who made it tho ahah

**Comment by SaraVieira** [comment]
Found who made it! Gonna add the link here
